spring:
  application:
    name: beribturing
  profiles:
    active: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: ${spring.application.name}
    password: ${spring.application.name}1234
    hikari:
      pool-name: HikariCP
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 15000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    out-of-order: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      database: 0
  jackson:
    default-property-inclusion: ALWAYS
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 20MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://beribturing-minio:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:test1234}
  bucket:
    name: ${MINIO_BUCKET_NAME:beribturing}
  publicUrl: ${MINIO_PUBLIC_URL:https://cdn.beribtur.ing/minio/ui}

server:
  port: 9093

beribturing:
  jwtSecret: ThisIsASecretKeySoLongThatEvenHackersWillGetBoredAndGiveUpBigIt12345YouShallNotPassMayTheTokenBeWithYouWhyAreYouStillReadingThisJustUseOAuth2Already
  jwtExpirationMs: 86400000 #24 hours
  refreshExpirationMs: 604800000 # week

otp:
  duration: #Units are in milliseconds
    sign-up: 180000    #3 minutes
    reset-password: 300000  #5 minutes

firebase:
  config:
    path: ./firebase.json

sms:
  gateway:
    url: http://notify.eskiz.uz/api/message/sms/send
    username: info.beribtur.ing@gmail.com
    token: test
    apiToken: test
  template:
    sign-up: "beribtur.ing'dan ro‘yxatdan o‘tish uchun tasdiqlash kodi:"
    reset-password: "beribtur.ing'da maxfiy so'zni o'zgartirish uchun tasdiqlash kodi:"
    test: "Bu Eskiz dan test"

management:
  endpoints.web.exposure.include: health, loggers, info, metrics, prometheus

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
