spring:
  application:
    name: beribturing
  profiles:
    active: default

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/beribturingdb2
    username: postgres
    password: root123
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    out-of-order: true

server:
  port: 9093

beribturing:
  jwtSecret: ThisIsASecretKeySoLongThatEvenHackersWillGetBoredAndGiveUpBigIt12345YouShallNotPassMayTheTokenBeWithYouWhyAreYouStillReadingThisJustUseOAuth2Already
  expiration: 86400000 #24 hours
  refresh-expiration: 604800000 # week

management:
  endpoints.web.exposure.include: health, loggers, info, metrics, prometheus

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html