name: Deploy on Push to main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH secrets (partial)
        run: |
          echo "HOST: ${{ secrets.SSH_HOST }}"
          echo "USER: ${{ secrets.SSH_USERNAME }}"
          echo "KEY Length: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l)"


      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo /usr/bin/git --git-dir=/opt/projects/backend/backend-beribturing/.git \
            --work-tree=/opt/projects/backend/backend-beribturing pull && \
            sudo /usr/bin/docker compose -f /opt/projects/backend/backend-beribturing/docker-compose.yml up --build -d
