name: Deploy on Push to main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 165.22.70.210
          username: root
          key: Theta17*
          script: |
            sudo /usr/bin/git --git-dir=/opt/projects/backend/dev/between-service/.git \
            --work-tree=/opt/projects/backend/dev/between-service pull && \
            sudo /usr/bin/docker compose -f /opt/projects/backend/dev/between-service/docker-compose.dev.yml up --build -d
